In [8]:
import torch
import numpy as np

## 张量创建与初始化

In [10]:
torch.tensor([1, 2, 3]) # 从现有的数据中创建tensor 可以是list 可以是numpy
torch.zeros(2, 3) # 创建固定形状的全0tensor ones()同理
torch.rand(2,2) # 均匀分布随机变量
torch.randn(2,2) # 标准正态分布随机变量
torch.arange(0, 10, 2) # 等差序列张量
torch.linspace(0, 1, 5) # 线性间隔张量
torch.eye(3) #单位对角矩阵
torch.empty(2,2) # 未初始化张量
torch.from_numpy(np.array([1, 2])) # numpy转张量

tensor([1, 2])

## 张量操作与变形

In [25]:
# reshape 或者 view改变张量的形状
x = torch.arange(0,18)
x1 = x.view(6,3)
x2 = x.reshape(2,3,3)

In [26]:
# torch.permute() 调整维度顺序
x1
x1.permute(1,0)  # 这样就相当于做了一个转置，这里面要填的是原本的维度的重新排序，这个例子的意思就是把原来的第一个维度放到现在第0个维度

tensor([[ 0,  3,  6,  9, 12, 15],
        [ 1,  4,  7, 10, 13, 16],
        [ 2,  5,  8, 11, 14, 17]])

In [31]:
# torch.transpose() 交换两个维度
print(x2)
print(x2.transpose(1,2)) # 填你想交换的两个维度

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])
tensor([[[ 0,  3,  6],
         [ 1,  4,  7],
         [ 2,  5,  8]],

        [[ 9, 12, 15],
         [10, 13, 16],
         [11, 14, 17]]])


In [30]:
# torch.squeeze() / unsqueeze() 添加或者删除一个长度为1 的维度

print(x1.shape)
print(x1.unsqueeze(dim=0).shape)
print(x1.squeeze(dim=0).shape)


torch.Size([6, 3])
torch.Size([1, 6, 3])
torch.Size([6, 3])


In [ ]:
# torch.cat() / stack() 拼接或者堆叠张量
a = torch.arange(0,20,2).reshape(2,5)
b = torch.arange(101,121,2).reshape(2,5)

cat_tensor = torch.cat([a,b], dim=0) # 在某个维度上进行拼接，总维度的数目不变 [(2,3), (2,3), dim=0] --> [(4,3)]
stack_tensor = torch.stack([a,b], dim=2) # 要求矩阵的形状必须完全相同，然后在dim指定的维度上插入一个新的维度，然后把矩阵融合起来

torch.Size([2, 5, 2])

In [53]:

tensor = torch.arange(18).reshape(6, 3)
split_result = torch.split(tensor, 1, dim=1)  # 根据你指定的维度，按照你指定的数组长度进行切割
split_result_uneven = torch.split(tensor, [1, 2, 3]) # 新的数组的形状可以不是均匀的，只要加起来和原来的维度上的维度数一样就好

In [ ]:
# torch.expand() / repeat()  扩展/重复张量（expand 不复制数据）
x = torch.tensor([[1, 2, 3]])
expanded_x = x.expand(4, 3)
print(expanded_x) # 按照广播机制，自动将数据扩展到指定的维度

x = torch.tensor([[1, 2, 3]])
repeat_x = x.repeat(2,1) # repeat 指定每个维度复制的次数，成倍的复制


tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])
tensor([[1, 2, 3],
        [1, 2, 3]])
